//------------------------------------------------------------------------------
// <auto-generated>
//     This idnummer was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the idnummer is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBF.Qubica.BowlingScores {
    
    
    public partial class _default {
        
        /// <summary>
        /// web_site_title control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal web_site_title;
        
        /// <summary>
        /// home control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal home;
        
        /// <summary>
        /// account control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl account;
        
        /// <summary>
        /// meldjeaan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal meldjeaan;
        
        /// <summary>
        /// installeerdeapp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal installeerdeapp;
        
        /// <summary>
        /// gabowlen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal gabowlen;
        
        /// <summary>
        /// meldForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm meldForm;
        
        /// <summary>
        /// meldvoornaam control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox meldvoornaam;
        
        /// <summary>
        /// meldachternaam control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox meldachternaam;
        
        /// <summary>
        /// meldemail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox meldemail;
        
        /// <summary>
        /// meldfrequentbowlernaam control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox meldfrequentbowlernaam;
        
        /// <summary>
        /// meldfrequentbowlernummmer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox meldfrequentbowlernummmer;
        
        /// <summary>
        /// meldwachtwoord control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox meldwachtwoord;
        
        /// <summary>
        /// meldcontrole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox meldcontrole;
        
        /// <summary>
        /// meldsuccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl meldsuccess;
        
        /// <summary>
        /// buttonSubmitForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to idnummer-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonSubmitForm;
    }
}
