//------------------------------------------------------------------------------
// <auto-generated>
//     This idnummer was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the idnummer is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBF.Qubica.BowlingScores {
    
    
    public partial class Logout {
    }
}
